#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

(
    container_id="$(create /opt/resource/check)"
    dir=$(mktemp -d -t test-check.XXXXX)

    it "produces a version on first run"
    init_kustomize_repo "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:1" "$dir"
    copy_kustomize_repo "$dir" "$container_id" remote-repo-v1

    assert_equal_json \
        '[ { tag:"1", app: "my-app" } ]' \
        "$(start_container "$container_id" '{
            source: { uri: "/tmp/remote-repo-v1", branch: "master", private_key: "something" }
        }')"

    it "produces multiple versions, given a prior version, on future runs"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:2"  "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:3"  "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/changed-app:4"  "$dir"
    copy_kustomize_repo "$dir" "$container_id" remote-repo-v2

    assert_equal_json \
        '[ { tag: "2", app: "changed-app"},
           { tag: "3", app: "changed-app"},
           { tag: "4", app: "changed-app"}
         ]' \
        "$(start_container "$container_id" '{
            source: { uri: "/tmp/remote-repo-v2", branch: "master", private_key: "something" },
            version: { tag: "2", app: "my-app" }
        }')"

    rm -rf "$dir"
    docker rm "$container_id" > /dev/null
)

it "successfully checks GitHub repo with explicit kustomization.yaml path"
frontend_uri="git@github.com:boclips/frontend.git"
frontend_private_key="$(bo show credential concourse-main boclips.frontend repo-key)"
frontend_commit_with_9_version=08d9a42b628a3c09ea8e42f915d69c97946170d7

frontend_input="$(
jq \
    --null-input \
    --arg uri "$frontend_uri" \
    --arg branch "$frontend_commit_with_9_version" \
    --arg private_key "$frontend_private_key" \
    '{
       source: {
         uri: $uri,
         branch: $branch,
         private_key: $private_key,
         kustomization_yaml_path: "k8s/boclips/base/kustomization.yaml"
       },
       version: {
         tag: "1"
       }
     }'
)"

assert_equal_json '
[
  { tag: "1", app: "boclips-frontend" },
  { tag: "2", app: "boclips-frontend" },
  { tag: "3", app: "boclips-frontend" },
  { tag: "4", app: "boclips-frontend" },
  { tag: "5", app: "boclips-frontend" },
  { tag: "6", app: "boclips-frontend" },
  { tag: "7", app: "boclips-frontend" },
  { tag: "8", app: "boclips-frontend" },
  { tag: "9", app: "boclips-frontend" }
]
' \
    "$(run /opt/resource/check "$frontend_input")"
