#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

backoffice_uri="git@github.com:boclips/backoffice.git"
backoffice_private_key="$(bo show credential concourse-main boclips.backoffice repo-key)"
backoffice_commit_with_150_version=ba1ad01e96bc2c3cb0236fd66f5f94b58ed84801

frontend_uri="git@github.com:boclips/frontend.git"
frontend_private_key="$(bo show credential concourse-main boclips.frontend repo-key)"
frontend_commit_with_9_version=08d9a42b628a3c09ea8e42f915d69c97946170d7

backoffice_input_initial="$(
jq \
    --null-input \
    --arg uri "$backoffice_uri" \
    --arg branch "$backoffice_commit_with_150_version" \
    --arg private_key "$backoffice_private_key" \
    '{
       source: {
         uri: $uri,
         branch: $branch,
         private_key: $private_key
       }
     }'
)"

backoffice_input="$(
jq \
    --null-input \
    --arg uri "$backoffice_uri" \
    --arg branch "$backoffice_commit_with_150_version" \
    --arg private_key "$backoffice_private_key" \
    '{
       source: {
         uri: $uri,
         branch: $branch,
         private_key: $private_key
       },
       version: {
         tag: "140"
       }
     }'
)"

frontend_input="$(
jq \
    --null-input \
    --arg uri "$frontend_uri" \
    --arg branch "$frontend_commit_with_9_version" \
    --arg private_key "$frontend_private_key" \
    '{
       source: {
         uri: $uri,
         branch: $branch,
         private_key: $private_key,
         kustomization_yaml_path: "k8s/boclips/base/kustomization.yaml"
       },
       version: {
         tag: "1"
       }
     }'
)"

expected_backoffice_output="$(cat <<EOF
[
  { "version": "140" },
  { "version": "141" },
  { "version": "142" },
  { "version": "143" },
  { "version": "144" },
  { "version": "145" },
  { "version": "146" },
  { "version": "147" },
  { "version": "148" },
  { "version": "149" },
  { "version": "150" }
]
EOF
)"

expected_frontend_output="$(cat <<EOF
[
  { "version": "1" },
  { "version": "2" },
  { "version": "3" },
  { "version": "4" },
  { "version": "5" },
  { "version": "6" },
  { "version": "7" },
  { "version": "8" },
  { "version": "9" }
]
EOF
)"

echo "check returns current version on first request"
assert_equal_json \
    '[ { "version": "150" } ]' \
    "$(run /opt/resource/check "$backoffice_input_initial")"

echo "check repo without explicit kustomization.yaml path"
assert_equal_json \
    "$expected_backoffice_output" \
    "$(run /opt/resource/check "$backoffice_input")"

echo "Can check twice, reusing the container"
assert_runs_twice /opt/resource/check "$backoffice_input"

echo "check repo with explicit kustomization.yaml path"
assert_equal_json \
    "$expected_frontend_output" \
    "$(run /opt/resource/check "$frontend_input")"
