#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

(
    container_id="$(create /opt/resource/check)"
    dir=$(mktemp -d -t test-check.XXXXX)

    it "produces a version on first run"
    init_kustomize_repo "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:1" "$dir"
    copy_kustomize_repo "$dir" "$container_id" remote-repo-v1

    assert_equal_json \
        '[ { tag:"1", app: "my-app" } ]' \
        "$(start_container "$container_id" '{
            source: {
                uri: "/tmp/remote-repo-v1",
                branch: "master",
                private_key: "something",
                kustomization_yaml_path: "k8s/base/kustomization.yaml"
            }
        }')"

    it "produces multiple versions, given a prior version, on future runs"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:2"  "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/my-app:3"  "$dir"
    commit_image "app=eu.gcr.io/boclips-prod/boclips/changed-app:4"  "$dir"
    copy_kustomize_repo "$dir" "$container_id" remote-repo-v2

    assert_equal_json \
        '[ { tag: "2", app: "changed-app"},
           { tag: "3", app: "changed-app"},
           { tag: "4", app: "changed-app"}
         ]' \
        "$(start_container "$container_id" '{
            source: {
                uri: "/tmp/remote-repo-v2",
                branch: "master",
                private_key: "something",
                kustomization_yaml_path: "k8s/base/kustomization.yaml"
            },
            version: { tag: "2", app: "my-app" }
        }')"

    rm -rf "$dir"
    docker rm "$container_id" > /dev/null
)

it "successfully checks GitHub repo"
uri="git@github.com:boclips/release-manifests.git"
private_key="$(bo show credential concourse-main boclips.release-manifests repo-key)"

input="$(
jq \
    --null-input \
    --arg uri "$uri" \
    --arg branch master \
    --arg private_key "$private_key" \
    '{
       source: {
         uri: $uri,
         branch: $branch,
         private_key: $private_key,
         kustomization_yaml_path: "k8s/gateway/base/kustomization.yaml"
       },
       version: {
         tag: "1"
       }
     }'
)"

assert_equal_json '
[
  { tag: "1", app: "gateway" },
  { tag: "2", app: "gateway" },
  { tag: "3", app: "gateway" },
  { tag: "4", app: "gateway" },
  { tag: "5", app: "gateway" },
  { tag: "6", app: "gateway" },
  { tag: "7", app: "gateway" },
  { tag: "8", app: "gateway" },
  { tag: "9", app: "gateway" },
  { tag: "10", app: "gateway" }
]
' \
    "$(run /opt/resource/check "$input" | jq '.[0:10]')"
