#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"

create () {
    image_id="$(cat "$cwd/../test_image_id")"
    docker create \
        --interactive \
        --entrypoint="$1" \
        "$image_id"
}

start_container () {
    container_id="$1"
    input="$2"
    docker start \
        --interactive \
        "$container_id" \
        <<< "$input"
}

run () {
    entrypoint="$1"
    input="$2"
    container_id="$(create "$entrypoint")"
    start_container "$container_id" "$input"
}

assert_runs_twice () {
    entrypoint="$1"
    input="$2"
    container_id="$(create "$entrypoint")"

    echo "Run 1"
    echo
    start_container "$container_id" "$input" > /dev/null
    echo
    echo "Run 2"
    echo
    if start_container "$container_id" "$input" > /dev/null
    then
        echo "Test passed"
    else
        echo "Test failed"
        exit 1
    fi
}

assert_equal_json () {
    assert_equal "$(jq <<< "$1")" "$(jq <<< "$2")"
}

assert_equal () {
    if [ "$1" == "$2" ]
    then
        echo "Test passed"
    else
        echo "Test failed"
        echo
        echo "Expected output:"
        echo "$1"
        echo
        echo "Actual output:"
        echo "$2"
        echo
        exit 1
    fi
}
