#!/usr/bin/env bash

run () {
    (
    image_id="$(docker build --quiet $1)"
    docker run \
        --interactive \
        --entrypoint="$2" \
        "$image_id" \
        <<< "$3"
    )
}

assert_equal_json () {
    comparable_actual_output="$(jq <<< "$2")"
    comparable_expected_output="$(jq <<< "$1")"
    if [ "$comparable_actual_output" == "$comparable_expected_output" ]
    then
        echo "Test passed"
    else
        echo "Test failed"
        echo
        echo "Expected output:"
        echo "$comparable_expected_output"
        echo
        echo "Actual output:"
        echo "$comparable_actual_output"
        echo
        exit 1
    fi
}
