---
jobs:

- name: build
  plan:
  - get: source
  - put: version
    params:
      bump: minor
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
          tag: "0.1.0"
      inputs:
      - name: source
      outputs:
      - name: image
      run:
        path: build
      caches:
      - path: cache
      params:
        CONTEXT: source
  - put: dockerhub
    params:
      image: image/image.tar
      additional_tags: version/version

- name: bump-version-playground
  plan:
  - put: version
    resource: test-repo-kustomize-version
  - task: cat-result
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bash
          tag: latest
      inputs:
      - name: version
      run:
        path: bash
        args:
        - -ec
        - |-
          cat version/tag
          cat version/app

- name: get-version-playground
  plan:
  - get: test-repo-kustomize-version

resources:

- name: source
  type: git
  icon: github-circle
  source:
    branch: master
    uri: https://github.com/boclips/kustomize-version-resource.git

- name: test-repo-kustomize-version
  type: kustomize-version
  icon: github-circle
  source:
    branch: master
    uri: git@github.com:boclips/kustomize-version-resource-test-repo.git
    private_key: ((kustomize-version-resource-test-repo.repo-key))

- name: version
  type: semver
  icon: github-circle
  source:
    driver: git
    uri: git@github.com:boclips/versions.git
    branch: master
    file: docker-image-kustomize-version-resource
    private_key: ((versions.repo-key))

- name: dockerhub
  type: registry-image
  icon: docker
  source:
    repository: boclipsconcourse/kustomize-version-resource
    username: boclipsconcourse
    password: ((docker-hub.password))

resource_types:

- name: kustomize-version
  type: registry-image
  source:
    repository: boclipsconcourse/kustomize-version-resource
    tag: latest
