#!/usr/bin/env bash

private_key_path=/tmp/clone_private_key

get () {
    jq --raw-output ".$1.$2 // empty"
}

validate_payload () {
    payload=$1
    uri="$(get source uri <<< "$payload")"
    private_key="$(get source private_key <<< "$payload")"
    kustomization_yaml_path="$(get source kustomization_yaml_path <<< "$payload")"
    if [ -z "$uri" ] \
        || [ -z "$private_key" ] \
        || [ -z "$kustomization_yaml_path" ]
    then
        log "Must provide uri, private_key and kustomization_yaml_path"
        exit 1
    fi
}

wrapped_git () {
    GIT_SSH_COMMAND="ssh -i $private_key_path" \
        git "$@"
}

clone () {
    uri="$1"
    destination="$2"
    echo "$3" > "$private_key_path"
    chmod 0600 "$private_key_path"

    mkdir --parents ~/.ssh
    touch ~/.ssh/known_hosts
    if ! grep -q github.com ~/.ssh/known_hosts
    then
        ssh-keyscan github.com \
            >> ~/.ssh/known_hosts \
            2> /dev/null
    fi

    if [ -d "$destination" ]
    then
        log "Pulling in existing repo, because $destination exists"
        wrapped_git -C "$destination" pull --quiet
    else
        log "Cloning the repo"
        wrapped_git clone --quiet "$uri" "$destination"
    fi
}

log () {
    >&2 echo "$@"
}
