#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

clone_dir=/tmp/kustomize-version-resource

export GIT_COMMITTER_NAME=Kustomizer
export GIT_COMMITTER_EMAIL=engineering@boclips.com

payload="$(cat)"
push="$cwd/push"
try_limit=5

validate_payload "$payload"

resources_root=$1

uri="$(get source uri <<< "$payload")"
private_key="$(get source private_key <<< "$payload")"
kustomization_yaml_path="$(get source kustomization_yaml_path <<< "$payload")"
version_file="$(get params file <<< "$payload")"
version="$(cat "$resources_root/$version_file")"

clone "$uri" "$clone_dir" "$private_key"
log "Successfully cloned $uri to $clone_dir"

app="$("$cwd/parse-app" "$clone_dir/$kustomization_yaml_path")"
log "Parsed app name as '$app'"

cd "$clone_dir/$(dirname "$kustomization_yaml_path")"

kustomize edit set image "app=eu.gcr.io/boclips-prod/boclips/$app:$version"
kustomize edit add annotation --force "boclips-version:$version"

git \
  commit \
  --quiet \
  --all \
  --author="$GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>" \
  --message="Bump $app version to $version"

for try in $(seq 1 $try_limit)
do
    $push "$clone_dir" "$try" "$try_limit"
done

jq \
    --null-input \
    --arg tag "$version" \
    --arg app "$app" \
    '{
       version: { tag: $tag, app: $app },
       metadata: [{ name: "tag", value: $tag }, { name: "app", value: $app }]
     }'
